kind: ConfigMap
apiVersion: v1
metadata:
  name: addressbook-config
data:
  application.yaml: |
    spring:
      r2dbc:
        url: r2dbc:postgres://db.java-middle.svc.cluster.local:5432/${POSTGRESQL_DATABASE}
        username: ${POSTGRESQL_USERNAME}
        password: ${POSTGRESQL_PASSWORD}
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQL95Dialect