kind: ConfigMap
apiVersion: v1
metadata:
  name: db-init-config
data:
  init-db.sql: |
    DROP TABLE IF EXISTS ADDRESS_BOOK;
    CREATE TABLE ADDRESS_BOOK (
      ID BIGSERIAL PRIMARY KEY,
      FIRST_NAME VARCHAR(50) NOT NULL,
      LAST_NAME VARCHAR(50) NOT NULL,
      PHONE VARCHAR(20) NOT NULL,
      BIRTHDAY DATE
    )