kind: ConfigMap
apiVersion: v1
metadata:
  name: addressbook-config
data:
  application.yaml: |
    spring:
      r2dbc:
        url: r2dbc:postgres://db.sbercode-cec8f8a3-4995-425c-865d-4ebe887697ac-work.svc.cluster.local:5432/${POSTGRESQL_DATABASE}
        username: ${POSTGRESQL_USERNAME}
        password: ${POSTGRESQL_PASSWORD}
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQL95Dialect